services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
      - PORT=80
    ports:
      - "8081:80"

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
      - PORT=80
    ports:
      - "8082:80"







